export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  ORGANIZATION: '/organization',
  ORGANIZATION_LIST: '/organization/list',
  DEPARTMENTS: '/organization/departments',
  BRANCHES: '/organization/branches',
  TEAMS: '/organization/teams',
  ASSETS: '/assets',
  BOOKINGS: '/booking/dashboard',
  BOOKING_DASHBOARD: '/booking/dashboard',
  BOOKING_MEETING_ROOMS: '/booking/meeting-rooms',
  BOOKING_VEHICLES: '/booking/vehicles',
  BOOKING_EQUIPMENT: '/booking/equipment',
  BOOKING_WORKSPACES: '/booking/workspaces',
  BOOKING_LABS: '/booking/labs',
  BOOKING_CALENDAR: '/booking/calendar',
  BOOKING_HISTORY: '/booking/history',
  BOOKING_DETAILS: '/booking/details/:id',
  BOOKING_APPROVALS: '/booking/approvals',
  MAINTENANCE: '/maintenance',
  AUDITS: '/audits',
  SETTINGS: '/settings',
  NOT_FOUND: '*',
};

